export const emoteList = {
    listemotes: 'lgbt2019, ffcheck, rpgbits, hahahalidays, luvcheck, hypetrain1, hypetrain2, lgbt2020, hyperscape, kpop, hindsight2020',
    lgbt2019: 'PrideLionYay PrideLionChomp PrideLionHey PrideBalloons PrideGive PrideTake PrideSaba PrideWingR PrideWingL PrideShine PrideParty PrideHi PrideGasp PrideFlag PrideCheers PridePan PrideAsexual PrideTrans PrideLesbian PrideBisexual',
    ffcheck: 'FightBerry FightBox FightBurger FightCC FightCookie FightFruit FightIce FightPC FightPepper FightPop FightSmore FightChips FightFry FightJello FightMash FightPizza FightPudding FightSardine FightSmoothie FightSoda FightSub FightBagel FightCake FightCheese FightCorn FightCup FightEgg FightNacho FightPBJ FightPie FightRamen FightSalad FightSoup FightSpag FightTomato',
    rpgbits: 'RPGAyaya RPGBukka RPGBukkaNoo RPGEmpty RPGEpicStaff RPGEpicSword RPGFei RPGFireball RPGGhosto RPGMana RPGOops RPGPhatLoot RPGShihu RPGStaff RPGTreeNua RPGYonger RPGHP RPGSeven',
    hahahalidays: 'HahaTurtledove HahaThisisfine HahaThink HahaSweat HahaSleep HahaShrugRight HahaShrugMiddle HahaShrugLeft HahaReindeer HahaPresent HahaSnowhal HahaPoint HahaNutcracker HahaLean HahaHide HahaGoose HahaGingercat HahaElf HahaDoge HahaCat HahaBaby HahaDreidel HahaBall Haha2020 HahaNyandeer',
    hypetrain1: 'Level 1 HypeGriffin1 HypeGriffin2 HypeGriffin3 HypeGriffin4 HypeGriffin5 HypeGriffin6 Level 2 HypeBigfoot1 HypeBigfoot2 HypeBigfoot3 HypeBigfoot4 HypeBigfoot5 HypeBigfoot6 Level 3 HypeOni1 HypeOni2 HypeOni3 HypeOni4 HypeOni5 HypeOni6 Level 4 HypeDragon1 HypeDragon2 HypeDragon3 HypeDragon4 HypeDragon5 HypeDragon6 Level 5 HypeUnicorn1 HypeUnicorn2 HypeUnicorn3 HypeUnicorn4 HypeUnicorn5 HypeUnicorn6',
    hypetrain2: 'Level 1 HypeChimp HypeGhost HypeChest HypeFrog HypeCherry (bonus: HypePeace ) Level 2 HypeSideeye HypeBrain HypeZap HypeShip HypeSign (bonus: HypeBug ) Level 3 HypeYikes HypeRacer HypeCar HypeFirst HypeTrophy (bonus: HypeBanana ) Level 4 HypeBlock HypeDaze HypeBounce HypeJewel HypeBlob (bonus: HypeTeamwork ) Level 5 HypeLove HypePunk HypeKO HypePunch HypeFire (bonus: HypePizza )',
    hypetrain3: 'Level 1 HypeFighter HypeShield HypeKick HypeSwipe HypeRip (bonus: HypeGG ) Level 2 HypeRanger HypeMiss HypeHit HypeHeart HypeTarget (bonus: HypeWink ) Level 3 HypeRogue HypeWut HypeGems HypeCoin HypeSneak (bonus: HypeCash ) Level 4 HypeBard HypeTune HypeRun HypeZzz HypeRock (bonus: HypeJuggle ) Level 5 HypeMage HypeWow HypeLol HypePotion HypeBook (bonus: HypeSmoke )',
    luvcheck: 'LuvBlondeL LuvBrownR LuvBrownL LuvBlondeR LuvPeekL LuvPeekR LuvBlush LuvSnooze LuvSign LuvHearts LuvGift LuvOops LuvUok LuvCool',
    lgbt2020: 'PrideDragon PrideCrown PrideWave PridePaint PrideWorld PrideCute PrideKoala PrideHeyyy PrideLove PrideStrong PrideUnicorn PridePog PrideUwu PrideRhino PridePenguin PrideLGBTea PrideToucan PrideFlower PrideHeartL PrideHeartR PrideLaugh PrideShrug PrideLion PrideRise PrideFloat',
    hyperscape: 'HyperLost HyperCrate HyperSlam HyperReveal HyperParkour HyperMine HyperMayhem HyperJump HyperHex HyperHaste HyperGravity HyperCrown HyperCooldown HyperCheese HyperTiger',
    kpop: 'KPOPselfie KPOPmerch KPOPheart KPOPfan KPOPdance KPOPcheer KPOPTT KPOPvictory KPOPlove KPOPglow',
    hindsight2020: '2020Celebrate 2020Shhh 2020Victory 2020MaskUp 2020Wish 2020Takeout 2020ByeGuys 2020Unity 2020Shred 2020Forward 2020Unroll 2020Drop 2020Glitchy 2020Partnered 2020Snacking 2020Suspicious 2020Surprise 2020SpeakUp 2020Selfie 2020Rivalry 2020Delivery 2020Gift 2020HomeWork 2020Pajamas 2020Party 2020Capture'
};